<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use app\models\active_queries\BarangQuery;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "barang".
 *
 * @property integer $id
 * @property string $nama
 * @property string $part_number
 * @property string $keterangan
 * @property string $ift_number
 * @property string $merk_part_number
 * @property integer $originalitas_id
 *
 * @property \app\models\BarangSatuan[] $barangSatuans
 * @property \app\models\FakturDetail[] $fakturDetails
 * @property \app\models\Originalitas $originalitas
 * @property string $aliasModel
 */
abstract class Barang extends ActiveRecord
{


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'barang';
    }

    /**
     * @inheritdoc
     * @return BarangQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new BarangQuery(get_called_class());
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['nama', 'ift_number', 'originalitas_id'], 'required'],
            [['keterangan'], 'string'],
            [['originalitas_id'], 'integer'],
            [['nama', 'merk_part_number'], 'string', 'max' => 255],
            [['part_number'], 'string', 'max' => 32],
            [['ift_number'], 'string', 'max' => 128],
            [['originalitas_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Originalitas::class, 'targetAttribute' => ['originalitas_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'part_number' => 'Part Number',
            'keterangan' => 'Keterangan',
            'ift_number' => 'Ift Number',
            'merk_part_number' => 'Merk Part Number',
            'originalitas_id' => 'Originalitas ID',
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getBarangSatuans()
    {
        return $this->hasMany(\app\models\BarangSatuan::class, ['barang_id' => 'id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getFakturDetails(): ActiveQuery
    {
        return $this->hasMany(\app\models\FakturDetail::class, ['barang_id' => 'id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getOriginalitas(): ActiveQuery
    {
        return $this->hasOne(\app\models\Originalitas::class, ['id' => 'originalitas_id']);
    }


}