<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use app\models\active_queries\ClaimPettyCashQuery;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "claim_petty_cash".
 *
 * @property integer $id
 * @property string $nomor
 * @property integer $vendor_id
 * @property string $tanggal
 * @property string $remarks
 * @property string $approved_by
 * @property string $acknowledge_by
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $created_by
 * @property string $updated_by
 *
 * @property \app\models\ClaimPettyCashNota[] $claimPettyCashNotas
 * @property \app\models\Card $vendor
 * @property string $aliasModel
 */
abstract class ClaimPettyCash extends ActiveRecord
{


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'claim_petty_cash';
    }

    /**
     * @inheritdoc
     * @return ClaimPettyCashQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ClaimPettyCashQuery(get_called_class());
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['vendor_id', 'tanggal', 'approved_by', 'acknowledge_by'], 'required'],
            [['vendor_id'], 'integer'],
            [['tanggal'], 'safe'],
            [['remarks'], 'string'],
            [['nomor'], 'string', 'max' => 128],
            [['approved_by', 'acknowledge_by'], 'string', 'max' => 255],
            [['vendor_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['vendor_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nomor' => 'Nomor',
            'vendor_id' => 'Vendor ID',
            'tanggal' => 'Tanggal',
            'remarks' => 'Remarks',
            'approved_by' => 'Approved By',
            'acknowledge_by' => 'Acknowledge By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getClaimPettyCashNotas()
    {
        return $this->hasMany(\app\models\ClaimPettyCashNota::class, ['claim_petty_cash_id' => 'id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getVendor()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'vendor_id']);
    }


}