<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "history_lokasi_barang".
 *
 * @property integer $id
 * @property integer $card_id
 * @property integer $tanda_terima_barang_detail_id
 * @property integer $claim_petty_cash_nota_detail_id
 * @property integer $tipe_pergerakan_id
 * @property integer $step
 * @property string $quantity
 * @property string $block
 * @property string $rak
 * @property string $tier
 * @property string $row
 * @property string $catatan
 *
 * @property \app\models\Card $card
 * @property \app\models\ClaimPettyCashNotaDetail $claimPettyCashNotaDetail
 * @property \app\models\TandaTerimaBarangDetail $tandaTerimaBarangDetail
 * @property \app\models\Status $tipePergerakan
 * @property string $aliasModel
 */
abstract class HistoryLokasiBarang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'history_lokasi_barang';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['card_id', 'quantity', 'block', 'rak', 'tier', 'row'], 'required'],
            [['card_id', 'tanda_terima_barang_detail_id', 'claim_petty_cash_nota_detail_id', 'tipe_pergerakan_id', 'step'], 'integer'],
            [['quantity'], 'number'],
            [['catatan'], 'string'],
            [['block', 'rak', 'tier', 'row'], 'string', 'max' => 8],
            [['card_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['card_id' => 'id']],
            [['tipe_pergerakan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Status::class, 'targetAttribute' => ['tipe_pergerakan_id' => 'id']],
            [['tanda_terima_barang_detail_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TandaTerimaBarangDetail::class, 'targetAttribute' => ['tanda_terima_barang_detail_id' => 'id']],
            [['claim_petty_cash_nota_detail_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ClaimPettyCashNotaDetail::class, 'targetAttribute' => ['claim_petty_cash_nota_detail_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'card_id' => 'Card ID',
            'tanda_terima_barang_detail_id' => 'Tanda Terima Barang Detail ID',
            'claim_petty_cash_nota_detail_id' => 'Claim Petty Cash Nota Detail ID',
            'tipe_pergerakan_id' => 'Tipe Pergerakan ID',
            'step' => 'Step',
            'quantity' => 'Quantity',
            'block' => 'Block',
            'rak' => 'Rak',
            'tier' => 'Tier',
            'row' => 'Row',
            'catatan' => 'Catatan',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'card_id' => 'Card yang bertindak sebagai warehouse',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCard()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'card_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClaimPettyCashNotaDetail()
    {
        return $this->hasOne(\app\models\ClaimPettyCashNotaDetail::class, ['id' => 'claim_petty_cash_nota_detail_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTandaTerimaBarangDetail()
    {
        return $this->hasOne(\app\models\TandaTerimaBarangDetail::class, ['id' => 'tanda_terima_barang_detail_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipePergerakan()
    {
        return $this->hasOne(\app\models\Status::class, ['id' => 'tipe_pergerakan_id']);
    }




}
