<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "purchase_order_detail".
 *
 * @property integer $id
 * @property integer $purchase_order_id
 * @property integer $barang_id
 * @property string $quantity
 * @property integer $satuan_id
 * @property string $price
 *
 * @property \app\models\Barang $barang
 * @property \app\models\PurchaseOrder $purchaseOrder
 * @property \app\models\Satuan $satuan
 * @property string $aliasModel
 */
abstract class PurchaseOrderDetail extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'purchase_order_detail';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['purchase_order_id', 'barang_id', 'satuan_id'], 'integer'],
            [['barang_id', 'satuan_id'], 'required'],
            [['quantity', 'price'], 'number'],
            [['barang_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Barang::class, 'targetAttribute' => ['barang_id' => 'id']],
            [['purchase_order_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\PurchaseOrder::class, 'targetAttribute' => ['purchase_order_id' => 'id']],
            [['satuan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Satuan::class, 'targetAttribute' => ['satuan_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'purchase_order_id' => 'Purchase Order ID',
            'barang_id' => 'Barang ID',
            'quantity' => 'Quantity',
            'satuan_id' => 'Satuan ID',
            'price' => 'Price',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBarang()
    {
        return $this->hasOne(\app\models\Barang::class, ['id' => 'barang_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPurchaseOrder()
    {
        return $this->hasOne(\app\models\PurchaseOrder::class, ['id' => 'purchase_order_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSatuan()
    {
        return $this->hasOne(\app\models\Satuan::class, ['id' => 'satuan_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\PurchaseOrderDetailQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\PurchaseOrderDetailQuery(get_called_class());
    }


}
