<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\active_queries\QuotationFormJobJobsQuery;

/**
 * This is the base-model class for table "quotation_form_job_jobs".
 *
 * @property integer $id
 * @property integer $quotation_form_job_id
 * @property string $nama
 * @property string $quantity
 * @property integer $satuan_id
 *
 * @property \app\models\QuotationFormJob $quotationFormJob
 * @property \app\models\Satuan $satuan
 */
abstract class QuotationFormJobJobs extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'quotation_form_job_jobs';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['quotation_form_job_id'], 'default', 'value' => null],
            [['quotation_form_job_id', 'satuan_id'], 'integer'],
            [['nama', 'quantity', 'satuan_id'], 'required'],
            [['quantity'], 'number'],
            [['nama'], 'string', 'max' => 255],
            [['quotation_form_job_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\QuotationFormJob::class, 'targetAttribute' => ['quotation_form_job_id' => 'id']],
            [['satuan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Satuan::class, 'targetAttribute' => ['satuan_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'quotation_form_job_id' => 'Quotation Form Job ID',
            'nama' => 'Nama',
            'quantity' => 'Quantity',
            'satuan_id' => 'Satuan ID',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuotationFormJob()
    {
        return $this->hasOne(\app\models\QuotationFormJob::class, ['id' => 'quotation_form_job_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSatuan()
    {
        return $this->hasOne(\app\models\Satuan::class, ['id' => 'satuan_id']);
    }

    /**
     * @inheritdoc
     * @return QuotationFormJobJobsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new QuotationFormJobJobsQuery(static::class);
    }
}
