<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\active_queries\QuotationFormJobQuery;

/**
 * This is the base-model class for table "quotation_form_job".
 *
 * @property integer $id
 * @property integer $quotation_id
 * @property string $nomor
 * @property integer $surat_perintah_kerja_id
 * @property string $surat_perintah_kerja_dos
 * @property string $tanggal
 * @property string $person_in_charge
 * @property string $issue
 * @property integer $card_own_equipment_id
 * @property string $hour_meter
 * @property integer $mekanik_id
 * @property string $remarks
 *
 * @property \app\models\CardOwnEquipment $cardOwnEquipment
 * @property \app\models\Card $mekanik
 * @property \app\models\Quotation $quotation
 * @property \app\models\QuotationFormJobJobs[] $quotationFormJobJobs
 * @property \app\models\QuotationFormJobMekanik[] $quotationFormJobMekaniks
 * @property \app\models\SuratPerintahKerja $suratPerintahKerja
 */
abstract class QuotationFormJob extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'quotation_form_job';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['quotation_id', 'nomor', 'surat_perintah_kerja_id', 'surat_perintah_kerja_dos', 'person_in_charge', 'issue', 'card_own_equipment_id', 'hour_meter', 'mekanik_id', 'remarks'], 'default', 'value' => null],
            [['quotation_id', 'surat_perintah_kerja_id', 'card_own_equipment_id', 'mekanik_id'], 'integer'],
            [['tanggal'], 'required'],
            [['tanggal'], 'safe'],
            [['issue', 'remarks'], 'string'],
            [['nomor', 'surat_perintah_kerja_dos', 'person_in_charge', 'hour_meter'], 'string', 'max' => 255],
            [['quotation_id'], 'unique'],
            [['mekanik_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['mekanik_id' => 'id']],
            [['card_own_equipment_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\CardOwnEquipment::class, 'targetAttribute' => ['card_own_equipment_id' => 'id']],
            [['quotation_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Quotation::class, 'targetAttribute' => ['quotation_id' => 'id']],
            [['surat_perintah_kerja_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\SuratPerintahKerja::class, 'targetAttribute' => ['surat_perintah_kerja_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'quotation_id' => 'Quotation ID',
            'nomor' => 'Nomor',
            'surat_perintah_kerja_id' => 'Surat Perintah Kerja ID',
            'surat_perintah_kerja_dos' => 'Surat Perintah Kerja Dos',
            'tanggal' => 'Tanggal',
            'person_in_charge' => 'Person In Charge',
            'issue' => 'Issue',
            'card_own_equipment_id' => 'Card Own Equipment ID',
            'hour_meter' => 'Hour Meter',
            'mekanik_id' => 'Mekanik ID',
            'remarks' => 'Remarks',
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return ArrayHelper::merge(parent::attributeHints(), [
            'surat_perintah_kerja_dos' => '(Optional) Surat Perintah Kerja yang dibuat di DOS jika dibuat di situ',
            'person_in_charge' => 'Perwakilan customer',
            'card_own_equipment_id' => 'Nomor Unit',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCardOwnEquipment()
    {
        return $this->hasOne(\app\models\CardOwnEquipment::class, ['id' => 'card_own_equipment_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMekanik()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'mekanik_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuotation()
    {
        return $this->hasOne(\app\models\Quotation::class, ['id' => 'quotation_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuotationFormJobJobs()
    {
        return $this->hasMany(\app\models\QuotationFormJobJobs::class, ['quotation_form_job_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuotationFormJobMekaniks()
    {
        return $this->hasMany(\app\models\QuotationFormJobMekanik::class, ['quotation_form_job_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSuratPerintahKerja()
    {
        return $this->hasOne(\app\models\SuratPerintahKerja::class, ['id' => 'surat_perintah_kerja_id']);
    }

    /**
     * @inheritdoc
     * @return QuotationFormJobQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new QuotationFormJobQuery(static::class);
    }
}
