<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\active_queries\QuotationFormJobSparePartQuery;

/**
 * This is the base-model class for table "quotation_form_job_spare_part".
 *
 * @property integer $id
 * @property integer $quotation_form_job_id
 * @property integer $barang_id
 * @property string $quantity
 * @property integer $satuan_id
 *
 * @property \app\models\Barang $barang
 * @property \app\models\QuotationFormJob $quotationFormJob
 * @property \app\models\Satuan $satuan
 */
abstract class QuotationFormJobSparePart extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'quotation_form_job_spare_part';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['quotation_form_job_id'], 'default', 'value' => null],
            [['quotation_form_job_id', 'barang_id', 'satuan_id'], 'integer'],
            [['barang_id', 'quantity', 'satuan_id'], 'required'],
            [['quantity'], 'number'],
            [['barang_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Barang::class, 'targetAttribute' => ['barang_id' => 'id']],
            [['quotation_form_job_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\QuotationFormJob::class, 'targetAttribute' => ['quotation_form_job_id' => 'id']],
            [['satuan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Satuan::class, 'targetAttribute' => ['satuan_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'quotation_form_job_id' => 'Quotation Form Job ID',
            'barang_id' => 'Barang ID',
            'quantity' => 'Quantity',
            'satuan_id' => 'Satuan ID',
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return ArrayHelper::merge(parent::attributeHints(), [
            'barang_id' => 'Dalam konteks ini, barang disebut sebagai Spare Part',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBarang()
    {
        return $this->hasOne(\app\models\Barang::class, ['id' => 'barang_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuotationFormJob()
    {
        return $this->hasOne(\app\models\QuotationFormJob::class, ['id' => 'quotation_form_job_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSatuan()
    {
        return $this->hasOne(\app\models\Satuan::class, ['id' => 'satuan_id']);
    }

    /**
     * @inheritdoc
     * @return QuotationFormJobSparePartQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new QuotationFormJobSparePartQuery(static::class);
    }
}
