<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\active_queries\QuotationServiceQuery;

/**
 * This is the base-model class for table "quotation_service".
 *
 * @property integer $id
 * @property integer $quotation_id
 * @property string $job_description
 * @property string $quantity
 * @property integer $satuan_id
 * @property string $rate
 * @property integer $discount
 * @property integer $is_vat
 *
 * @property \app\models\Quotation $quotation
 * @property \app\models\Satuan $satuan
 */
abstract class QuotationService extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'quotation_service';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['quotation_id', 'quantity', 'satuan_id', 'rate', 'discount'], 'default', 'value' => null],
            [['is_vat'], 'default', 'value' => 0],
            [['quotation_id', 'satuan_id', 'discount', 'is_vat'], 'integer'],
            [['job_description'], 'required'],
            [['quantity', 'rate'], 'number'],
            [['job_description'], 'string', 'max' => 255],
            [['quotation_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Quotation::class, 'targetAttribute' => ['quotation_id' => 'id']],
            [['satuan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Satuan::class, 'targetAttribute' => ['satuan_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'quotation_id' => 'Quotation ID',
            'job_description' => 'Job Description',
            'quantity' => 'Quantity',
            'satuan_id' => 'Satuan ID',
            'rate' => 'Rate',
            'discount' => 'Discount',
            'is_vat' => 'Is Vat',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuotation()
    {
        return $this->hasOne(\app\models\Quotation::class, ['id' => 'quotation_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSatuan()
    {
        return $this->hasOne(\app\models\Satuan::class, ['id' => 'satuan_id']);
    }

    /**
     * @inheritdoc
     * @return QuotationServiceQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new QuotationServiceQuery(static::class);
    }
}
