<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\active_queries\SuratPerintahKerjaDetailQuery;

/**
 * This is the base-model class for table "surat_perintah_kerja_detail".
 *
 * @property integer $id
 * @property integer $surat_perintah_kerja_id
 * @property string $waktu
 * @property string $keterangan
 *
 * @property \app\models\SuratPerintahKerja $suratPerintahKerja
 */
abstract class SuratPerintahKerjaDetail extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'surat_perintah_kerja_detail';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['surat_perintah_kerja_id'], 'default', 'value' => null],
            [['surat_perintah_kerja_id'], 'integer'],
            [['waktu', 'keterangan'], 'required'],
            [['waktu'], 'safe'],
            [['keterangan'], 'string'],
            [['surat_perintah_kerja_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\SuratPerintahKerja::class, 'targetAttribute' => ['surat_perintah_kerja_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'surat_perintah_kerja_id' => 'Surat Perintah Kerja ID',
            'waktu' => 'Waktu',
            'keterangan' => 'Keterangan',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSuratPerintahKerja()
    {
        return $this->hasOne(\app\models\SuratPerintahKerja::class, ['id' => 'surat_perintah_kerja_id']);
    }

    /**
     * @inheritdoc
     * @return SuratPerintahKerjaDetailQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new SuratPerintahKerjaDetailQuery(static::class);
    }
}
