<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\active_queries\SuratPerintahKerjaQuery;

/**
 * This is the base-model class for table "surat_perintah_kerja".
 *
 * @property integer $id
 * @property string $nomor
 * @property string $tanggal
 * @property string $pelaksana
 * @property string $judul
 * @property string $keterangan
 * @property string $data_pendukung_lainnya
 *
 * @property \app\models\SuratPerintahKerjaDetail[] $suratPerintahKerjaDetails
 * @property \app\models\SuratPerintahKerjaSupportingDocument[] $suratPerintahKerjaSupportingDocuments
 */
abstract class SuratPerintahKerja extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'surat_perintah_kerja';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['nomor', 'data_pendukung_lainnya'], 'default', 'value' => null],
            [['tanggal', 'pelaksana', 'judul', 'keterangan'], 'required'],
            [['tanggal'], 'safe'],
            [['keterangan', 'data_pendukung_lainnya'], 'string'],
            [['nomor', 'pelaksana', 'judul'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'nomor' => 'Nomor',
            'tanggal' => 'Tanggal',
            'pelaksana' => 'Pelaksana',
            'judul' => 'Judul',
            'keterangan' => 'Keterangan',
            'data_pendukung_lainnya' => 'Data Pendukung Lainnya',
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return ArrayHelper::merge(parent::attributeHints(), [
            'keterangan' => 'Deksripsi Pekerjaan Secara Umum',
            'data_pendukung_lainnya' => 'Data Pendukung Lainnya, Contoh: Customer P.O, Email Direksi, dll',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSuratPerintahKerjaDetails()
    {
        return $this->hasMany(\app\models\SuratPerintahKerjaDetail::class, ['surat_perintah_kerja_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSuratPerintahKerjaSupportingDocuments()
    {
        return $this->hasMany(\app\models\SuratPerintahKerjaSupportingDocument::class, ['surat_perintah_kerja_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return SuratPerintahKerjaQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new SuratPerintahKerjaQuery(static::class);
    }
}
