<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\active_queries\SuratPerintahKerjaSupportingDocumentQuery;

/**
 * This is the base-model class for table "surat_perintah_kerja_supporting_document".
 *
 * @property integer $id
 * @property integer $surat_perintah_kerja_id
 * @property integer $quotation_id
 *
 * @property \app\models\Quotation $quotation
 * @property \app\models\SuratPerintahKerja $suratPerintahKerja
 */
abstract class SuratPerintahKerjaSupportingDocument extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'surat_perintah_kerja_supporting_document';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['surat_perintah_kerja_id', 'quotation_id'], 'default', 'value' => null],
            [['surat_perintah_kerja_id', 'quotation_id'], 'integer'],
            [['quotation_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Quotation::class, 'targetAttribute' => ['quotation_id' => 'id']],
            [['surat_perintah_kerja_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\SuratPerintahKerja::class, 'targetAttribute' => ['surat_perintah_kerja_id' => 'id']]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'surat_perintah_kerja_id' => 'Surat Perintah Kerja ID',
            'quotation_id' => 'Quotation ID',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuotation()
    {
        return $this->hasOne(\app\models\Quotation::class, ['id' => 'quotation_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSuratPerintahKerja()
    {
        return $this->hasOne(\app\models\SuratPerintahKerja::class, ['id' => 'surat_perintah_kerja_id']);
    }

    /**
     * @inheritdoc
     * @return SuratPerintahKerjaSupportingDocumentQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new SuratPerintahKerjaSupportingDocumentQuery(static::class);
    }
}
